-- Create a dedicated database and schema for the data product
CREATE DATABASE IF NOT EXISTS TPCH_DATA_PRODUCT;
CREATE SCHEMA IF NOT EXISTS TPCH_DATA_PRODUCT.ANALYTICS;
USE SCHEMA TPCH_DATA_PRODUCT.ANALYTICS;

-- Grant Cortex User role
USE ROLE ACCOUNTADMIN; -- Or a role with SECURITYADMIN/OWNERSHIP
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACCOUNTADMIN;
