-- Silver Layer: Integrated Sales View
-- Combines data from TPCH sample database to create a unified sales view
CREATE OR REPLACE TABLE V_INTEGRATED_SALES AS
SELECT 
    o.O_ORDERKEY AS Order_ID,
    o.O_ORDERDATE AS Order_Date,
    c.C_NAME AS Customer_Name,
    c.C_MKTSEGMENT AS Market_Segment,
    n.N_NAME AS Nation,
    r.R_NAME AS Region,
    p.P_NAME AS Product_Name,
    p.P_TYPE AS Product_Type,
    l.L_QUANTITY AS Quantity,
    l.L_EXTENDEDPRICE AS Gross_Revenue,
    l.L_DISCOUNT AS Discount_Rate,
    (l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS Net_Revenue,
    l.L_LINESTATUS AS Line_Status
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART p ON l.L_PARTKEY = p.P_PARTKEY;
